#!/bin/bash

# Path to data
pathToData='./data/config_39/'

for i in 1 3 5 7 9 11 13 15 17 19 21 23;
do
        echo $i
        srun --comment="$@VUV_Ray_Trace $i" python /data/snoplus/home/jordan/VUV_Analysis/geoFactorAnalysis/testScripts/batchReader.py $i 2 $pathToData &
        sleep 0.1
done

