#!/bin/python
"""
Chris Benson
10/2/2015

This scrip generates macros needed to do a source position and intensity dependent study on the geometric factor.
"""
import json

numPhotons = 500000

#### Extract the source coordinates
coordFile = open('./sourceCoords.json').read()
coordData = json.loads(coordFile)

for line in coordData:
    
    macroFileName = './macros/'+'pos'+str(line['node'])+'.mac'

    masterString = '#Autogenerated by: ../sourceMacroGen.py\n#Written By: Chris Benson\n#10/2/2015\n\n'
    masterString += '/glg4debug/glg4param omit_muon_processes  1.0\n/glg4debug/glg4param omit_hadronic_processes  1.0\n\n'
    masterString += '/rat/db/set DETECTOR geo_file "VUV/VUV.geo"\n\n'
    masterString += '/run/initialize\n\n'
    masterString += '/rat/proc count\n/rat/procset update 1000\n\n'
    masterString += '/rat/proclast outroot\n\n'
    masterString += '/tracking/storeTrajectory 1\n\n'
    masterString += '/generator/add combo gun2:point\n'
    masterString += '/generator/vtx/set opticalphoton  1  0  0 '+str(2.0)+' 0.00000539062 0.00000539062\n' # Photon at 230 nm generated in a cone with opening angle of 3 degrees.
    masterString += '/generator/pos/set '+str(line['x'])+' '+str(line['y'])+' '+str(line['z'])+'\n\n'
    masterString += '/run/beamOn '+str(int(numPhotons))+'\n\n'

    # Write macro string to file.
    macOut = open(macroFileName,'w')
    macOut.write(masterString)
    macOut.close()






