#!/bin/python
"""
Chris Benson
10/2/2015

This scrip generates macros needed to do a source position and intensity dependent study on the geometric factor.
"""
import os, shutil
import sys

argss = sys.argv

pathToMacroStorage = '/data/snoplus/home/cbenson/VUV/macros/sourceMacros/'
openingAngleofGunCone = 3
numPhotonsGen = argss[1]

XposVect = [12.545000000000002, 14.450000000000001, 16.355, 18.26, 20.165, 22.07, 23.975, 25.88, 27.785, 29.689999999999998, 31.595]
YposVect = [-9.524999999999999, -7.619999999999999, -5.715, -3.8099999999999996, -1.9049999999999998, 0.0, 1.9049999999999998, 3.8099999999999996, 5.715, 7.619999999999999, 9.524999999999999]

XIntensityVect = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
YIntensityVect = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

# Before we generate any macros, we want to make sure that all previous macros have been deleted.

for the_file in os.listdir(pathToMacroStorage):
    file_path = os.path.join(pathToMacroStorage, the_file)
    try:
        if os.path.isfile(file_path):
            os.unlink(file_path)
        #elif os.path.isdir(file_path): shutil.rmtree(file_path)
    except Exception, e:
        print e

# start in bottom left corner and work way to top right left to right then bottom to top
positionCounter = 0
for yIndex,ypos in enumerate(YposVect):
	for xIndex,xpos in enumerate(XposVect):
		positionCounter += 1
		macroFileName = pathToMacroStorage+'pos'+str(positionCounter)+'.mac'
		
		masterString = '#Autogenerated by: ../sourceMacroGen.py\n#Written By: Chris Benson\n#10/2/2015\n\n'
		masterString += '/glg4debug/glg4param omit_muon_processes  1.0\n/glg4debug/glg4param omit_hadronic_processes  1.0\n\n'
		masterString += '/rat/db/set DETECTOR experiment "VUV"\n/rat/db/set DETECTOR geo_file "VUV/VUV.geo"\n\n'
		masterString += '/run/initialize\n\n'
		masterString += '/rat/proc count\n/rat/procset update 1000\n\n'
		masterString += '/rat/proclast outroot\n\n'
		masterString += '/tracking/storeTrajectory 1\n\n'
		masterString += '/generator/add combo gun2:point\n'
		masterString += '/generator/vtx/set opticalphoton  1  0  0 '+str(openingAngleofGunCone)+' 0.00000539062 0.00000539062\n' # Photon at 230 nm generated in a cone with opening angle of 3 degrees.
		masterString += '/generator/pos/set '+str(-38.58)+' '+str(xpos)+' '+str(ypos)+'\n\n'
		masterString += '/run/beamOn '+str(int(int(numPhotonsGen)*XIntensityVect[xIndex]*YIntensityVect[yIndex]))+'\n\n'
		
		# Write macro string to file.
		macOut = open(macroFileName,'w')
		macOut.write(masterString)
		macOut.close()






